In [1]:
a=10

In [5]:
1+4 

5

In [9]:
b = 0.35

In [11]:
b+0.1 #오류 이유 : 부동소수점이 내부적으로 이진법을 사용하기 때문에.

0.44999999999999996

#### 문자열

In [15]:
'http://www.python.org'.strip('htp:/')   #왜 자르는게 다른데 왜 다 지워지지?? ->들어간 문자열 순서대로 다 지우는듯

'www.python.org'

In [30]:
import re #문자열 정규표현식

In [31]:
series =""" '01/18/2014 13:00:00',100','1st';
            '01/18/2014 13:30:00',110','2nd';
            '01/18/2014 14:00:00',120','3rd'
            """   #""" 이러면 여러 줄에 걸친 문자열을 정의하는 것 가능"""

In [38]:
dt = re.compile("'[0-9/:\s]+'") #datetime    #backslach 대신 \사용

In [51]:
result = dt.findall(series)   #?
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

In [2]:
#날짜, 시간정보
from datetime import datetime

In [47]:
pydt = datetime.strptime(result[0].replace("'",""),
               '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [48]:
print(pydt)   #지금 날짜로는 어떻게? ->부록c

2014-01-18 13:00:00


In [50]:
datetime.today()

datetime.datetime(2020, 10, 1, 0, 22, 48, 982467)

In [3]:
datetime.now()

datetime.datetime(2020, 10, 1, 1, 23, 15, 839272)

#### 기본 자료구조

##### Tuple

In [53]:
t = (1,2.4,'data') #튜플 - () list - []
type(t)

tuple

In [54]:
t = 1,2.5,'data'
type(t)

tuple

#### numpy

In [5]:
l = [1,2.5,'data']
l.append([4,3])
l.extend([1.0,1.5,2.0])
l.insert(1,'insert') # index 앞에 원소 추가
l.remove('data')
p = l.pop(3)
print(l,p)

[1, 'insert', 2.5, 1.0, 1.5, 2.0] [4, 3]


In [13]:
r =list(range(0,8,1))
r

[0, 1, 2, 3, 4, 5, 6, 7]

In [10]:
m = [i**2 for i in range(5)]
m

[0, 1, 4, 9, 16]

In [3]:
from functools import reduce

In [1]:
import random
I = 5000
%time mat = [[random.gauss(0,1) for j in range(I)] for i in range(I)]

Wall time: 59.9 s


In [6]:
%time reduce(lambda x,y:x+y,[reduce(lambda x,y : x+y,row) for row in mat] )

Wall time: 6.87 s


-1530.3540895978879

In [ ]:
# dictionary -> import six 해야함 six.iteritems()로 변환됨

4-3-3 구조화 배열

In [3]:
import numpy as np

dt = np.dtype([('Name','S10'),('Age','i4'),
              ('Height','f'),('Children/Pets','i4',2)])
s = np.array([('happy',45,1.83,(0,1)),
             ('Jones',53,1.72,(2,2))], dtype = dt)       #b가 왜붙지..?
s

array([(b'happy', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [4]:
s['Name']

array([b'happy', b'Jones'], dtype='|S10')

In [4]:
s[1]['Age']

53

#### 4-4 코드 벡터화

4-4-1 기본적인 벡터화

In [5]:
r = np.random.standard_normal((4,3))
s = np.random.standard_normal((4,3))
r + s

array([[-0.33034789, -0.0125196 , -0.00449011],
       [ 0.06663079, -0.57958476,  2.11495174],
       [ 2.06358684,  1.10150721,  1.05982967],
       [-1.18685438,  0.44248739, -2.44383824]])

In [6]:
r

array([[ 0.25260808, -0.86657167, -0.03834046],
       [-0.11542759, -1.26372304,  1.73946579],
       [ 0.89353992,  1.3951493 ,  0.29194315],
       [ 0.45180582,  1.26624463, -0.71992527]])

In [6]:
2*r+3

array([[3.24686454, 7.07374741, 4.53874923],
       [1.40281036, 2.4833063 , 0.81338436],
       [1.942155  , 3.8087184 , 3.92859301],
       [2.60168467, 3.58457647, 0.60737346]])

In [7]:
s1 = np.random.standard_normal(3)
s1

array([-0.5526401 , -0.7912488 ,  0.47784057])

In [8]:
r

array([[ 0.25260808, -0.86657167, -0.03834046],
       [-0.11542759, -1.26372304,  1.73946579],
       [ 0.89353992,  1.3951493 ,  0.29194315],
       [ 0.45180582,  1.26624463, -0.71992527]])

In [9]:
r+s1   #s1원을 r의 각 행에 더함

array([[-0.30003202, -1.65782047,  0.43950011],
       [-0.6680677 , -2.05497184,  2.21730636],
       [ 0.34089982,  0.6039005 ,  0.76978372],
       [-0.10083428,  0.47499583, -0.2420847 ]])

In [12]:
s2 = np.random.standard_normal(4)
r+s2 #row 크기가달라서

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [13]:
s3 = np.random.standard_normal((3,4))
r.transpose()+s3

array([[-1.10443777, -0.01629239,  1.37861541,  0.52185026],
       [ 3.84189358, -0.12815006, -0.70455699,  1.02094156],
       [-1.11527465, -2.11005473,  0.76041953, -0.05247096]])

In [14]:
def f(x) :
    return 3*x+5

In [15]:
f(0.5)

6.5

In [16]:
f(r)   #각 원소마다 가능

array([[ 5.3702968 , 11.11062112,  7.30812385],
       [ 2.60421553,  4.22495945,  1.72007654],
       [ 3.41323249,  6.2130776 ,  6.39288951],
       [ 4.402527  ,  5.87686471,  1.41106019]])

In [19]:
import math

In [20]:
math.sin(r)

TypeError: only size-1 arrays can be converted to Python scalars

In [21]:
np.sin(r)   #math 함수로는 numpy배열 성립 X -> np에서 유니버셜함수 제공

array([[ 0.12311908,  0.89333793,  0.69568613],
       [-0.71637639, -0.25548261, -0.88815188],
       [-0.50460337,  0.39342972,  0.44779389],
       [-0.19784372,  0.28814416, -0.93069684]])

In [22]:
np.sin(np.pi)

1.2246467991473532e-16

4-4-2 메모리 배치

In [28]:
x = np.random.standard_normal((5,10000000))
y = 2*x+3
C = np.array((x,y),order = 'C')
F = np.array((x,y),order = 'F')
x = 0.0 ; y = 0.0 #memory cleanup

In [14]:
C.round(2)

array([[[ 0.24,  0.07,  0.41, ...,  0.02,  1.03,  0.13],
        [-0.84, -0.8 ,  0.43, ..., -0.48, -0.34,  0.98],
        [ 1.79,  1.37, -0.23, ..., -0.89, -0.07, -0.01],
        [ 0.73, -0.5 ,  1.23, ..., -1.35,  0.23,  0.06],
        [ 0.4 , -0.92, -1.5 , ..., -0.53, -0.51,  0.39]],

       [[ 3.47,  3.13,  3.82, ...,  3.03,  5.06,  3.26],
        [ 1.32,  1.4 ,  3.85, ...,  2.03,  2.31,  4.97],
        [ 6.59,  5.74,  2.53, ...,  1.22,  2.86,  2.98],
        [ 4.47,  2.01,  5.46, ...,  0.31,  3.46,  3.12],
        [ 3.81,  1.16, -0.01, ...,  1.94,  1.98,  3.77]]])

In [13]:
F.round(2)

array([[[ 0.24,  0.07,  0.41, ...,  0.02,  1.03,  0.13],
        [-0.84, -0.8 ,  0.43, ..., -0.48, -0.34,  0.98],
        [ 1.79,  1.37, -0.23, ..., -0.89, -0.07, -0.01],
        [ 0.73, -0.5 ,  1.23, ..., -1.35,  0.23,  0.06],
        [ 0.4 , -0.92, -1.5 , ..., -0.53, -0.51,  0.39]],

       [[ 3.47,  3.13,  3.82, ...,  3.03,  5.06,  3.26],
        [ 1.32,  1.4 ,  3.85, ...,  2.03,  2.31,  4.97],
        [ 6.59,  5.74,  2.53, ...,  1.22,  2.86,  2.98],
        [ 4.47,  2.01,  5.46, ...,  0.31,  3.46,  3.12],
        [ 3.81,  1.16, -0.01, ...,  1.94,  1.98,  3.77]]])

In [27]:
%timeit C.sum()

271 ms ± 39.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
%timeit F.sum()  #전체합 시 큰 차이 없음

245 ms ± 16.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
%timeit C[0].sum(axis = 0)

166 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
%timeit C[0].sum(axis = 1)

114 ms ± 3.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
%timeit F.sum(axis = 0)

1.56 s ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%timeit F.sum(axis = 1)

4.13 s ± 41.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
F = 0.0 ; C = 0.0

In [33]:
F

array([[[-1.16937818, -0.78869819,  1.37885251, ...,  0.57147749,
         -0.38019997,  2.22482244],
        [-0.02090714, -0.04405681, -0.57115207, ...,  1.31468894,
         -1.07831087, -1.12800291],
        [-1.7120799 , -1.14098773, -0.24576987, ..., -0.42090759,
          0.44075773, -0.31893459],
        [-0.17933413, -0.22959093, -1.29356472, ..., -2.34582868,
         -1.69156677, -0.05907884],
        [-0.0538165 , -0.73448823,  1.71497614, ..., -0.077166  ,
         -0.41048103,  1.45566219]],

       [[ 0.66124363,  1.42260362,  5.75770502, ...,  4.14295498,
          2.23960005,  7.44964487],
        [ 2.95818573,  2.91188638,  1.85769587, ...,  5.62937789,
          0.84337826,  0.74399418],
        [-0.42415981,  0.71802453,  2.50846026, ...,  2.15818482,
          3.88151547,  2.36213082],
        [ 2.64133173,  2.54081815,  0.41287057, ..., -1.69165736,
         -0.38313355,  2.88184231],
        [ 2.892367  ,  1.53102354,  6.42995229, ...,  2.84566801,
          2.17

In [34]:
C

array([[[-1.16937818, -0.78869819,  1.37885251, ...,  0.57147749,
         -0.38019997,  2.22482244],
        [-0.02090714, -0.04405681, -0.57115207, ...,  1.31468894,
         -1.07831087, -1.12800291],
        [-1.7120799 , -1.14098773, -0.24576987, ..., -0.42090759,
          0.44075773, -0.31893459],
        [-0.17933413, -0.22959093, -1.29356472, ..., -2.34582868,
         -1.69156677, -0.05907884],
        [-0.0538165 , -0.73448823,  1.71497614, ..., -0.077166  ,
         -0.41048103,  1.45566219]],

       [[ 0.66124363,  1.42260362,  5.75770502, ...,  4.14295498,
          2.23960005,  7.44964487],
        [ 2.95818573,  2.91188638,  1.85769587, ...,  5.62937789,
          0.84337826,  0.74399418],
        [-0.42415981,  0.71802453,  2.50846026, ...,  2.15818482,
          3.88151547,  2.36213082],
        [ 2.64133173,  2.54081815,  0.41287057, ..., -1.69165736,
         -0.38313355,  2.88184231],
        [ 2.892367  ,  1.53102354,  6.42995229, ...,  2.84566801,
          2.17