### Graphical User Interfaces(GUI)

**Short rate with GUI**


In [5]:
import numpy as np
import traits.api as trapi

In [6]:
class short_rate(trapi.HasTraits):
    name = trapi.Str
    rate = trapi.Float
    time_list = trapi.Array(dtype = np.float, shape = (5,))
    def get_discount_factors(self):
        return np.exp(-self.rate*self.time_list)

In [7]:
sr = short_rate()

In [8]:
sr.configure_traits() #값 넣을 수 있음

True

In [9]:
#코드로 쳐도 무관
sr.name = 'sr_class'
sr.rate = 0.05
sr.time_list = [0.0,0.5,1.0,1.5,2.0]

In [10]:
sr.rate, sr.time_list, sr.get_discount_factors()

(0.05,
 array([0. , 0.5, 1. , 1.5, 2. ]),
 array([1.        , 0.97530991, 0.95122942, 0.92774349, 0.90483742]))

**updating of values**

In [11]:
import traitsui.api as trui

In [26]:
class short_rate(trapi.HasTraits):
    name = trapi.Str
    rate = trapi.Float
    time_list = trapi.Array(dtype = np.float, shape = (1,5))
    disc_list = trapi.Array(dtype = np.float, shape = (1,5))
    update = trapi.Button
    def _update_fired(self):
        self.disc_list = np.exp(-self.rate*self.time_list)
    v = trui.View(trui.Group(trui.Item(name = 'name'),
                            trui.Item(name = 'rate'),
                            trui.Item(name = 'time_list',
                                      label = 'Insert Time List Here'),
                            trui.Item('update',show_label = False),
                            trui.Item(name = 'disc_list',
                                      label = 'Press Update for Factors'),
                            show_border = True, label = 'Calculate Discount Factors'),
                 buttons = [trui.OKButton, trui.CancelButton],
                 resizable = True)

In [27]:
sr = short_rate()

In [31]:
sr.configure_traits()

True

In [29]:
sr.name = 'sr_class'
sr.rate = 0.05
sr.time_list = np.array(([0.0,0.5,1.0,1.5,2.0],), dtype = np.float32)

In [30]:
sr._update_fired()  #이 이후에 sr.configure_traits 하면 update된 값 나옴

In [33]:
sr.disc_list

array([[1.        , 0.97530991, 0.95122942, 0.92774349, 0.90483742]])

In [43]:
class cash_flow_series(trapi.HasTraits):
    name = trapi.Str
    short_rate = trapi.Range(0.0,0.5,0.05)  #시간에 따라 달라지는 이자율
    time_list = trapi.Array(dtype = np.float,shape = (1,6))
    cash_flows = trapi.Array(dtype = np.float, shape = (1,6))
    disc_values = trapi.Array(dtype = np.float, shape = (1,6))
    present_values = trapi.Array(dtype = np.float, shape = (1,6))
    net_present_value = trapi.Float
    update = trapi.Button
    def _update_fired(self):
        self.disc_values = np.exp(-self.short_rate*self.time_list)
        self.present_values = self.disc_values*self.cash_flows
        self.net_present_value = np.sum(self.present_values)
    v = trui.View(trui.Group(trui.Item(name = 'name'),
                            trui.Item(name = 'short_rate'),
                            trui.Item(name = 'time_list', label = 'Time List'),
                            trui.Item(name = 'cash_flows', label = 'Cash Flows'),
                            trui.Item('update',show_label = False),
                            trui.Item(name = 'disc_values',
                                     label = 'Discount Factors'),
                            trui.Item(name = 'present_values',
                                     label = 'Present Values'),
                            trui.Item(name = 'net_present_value',
                                     label = 'NPV'),
                            show_border = True, label = 'Calculate Present Values'),
                 resizable = True)

In [44]:
cfs = cash_flow_series()

In [45]:
cfs.configure_traits()

True

In [46]:
cfs.net_present_value #인터페이스 안에서 바로 해씀

-0.2926769754325136